### ISSUE TITLE
mingW-gcc for window10

### ISSUE THREAD

**Issue by fengyanWang** [iwatake2222/play_with_ncnn#4]
Thank you very much for such a great open source project. I see that MSVC tools are used to build Windows Platforms in your project. I would like to ask how to modify the compilation link if I want to change to MinGW tools? Look forward to your reply!

![image](https://user-images.githubusercontent.com/36984088/132617127-c08fe8cd-4abb-43d4-aa46-0ccb0cbd87e7.png)

**Comment by iwatake2222** [comment]
The prebuilt library is created using Visual Studio 2019, and I don't think it's compatible with MinGW gcc/g++.
So, I suggest you build the library using MinGW in your environment (I'm not sure if ncnn can be built with MinGW though...)
Then, modify the cmake file like the following, assuming you place the created library in `ncnn_prebuilt/x64_windows_mingw`

before:
```cmake
elseif(MSVC_VERSION)
    set(NCNN_LIB
        $<$<CONFIG:Debug>:${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows/lib/ncnnd.lib>
        $<$<CONFIG:RelWithDebInfo>:${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows/lib/ncnnRelWithDebInfo.lib>
        $<$<CONFIG:Release>:${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows/lib/ncnn.lib>
        $<$<CONFIG:MinSizeRel>:${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows/lib/ncnnMinSizeRel.lib>
    )
    set(NCNN_INC ${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows/include/ncnn)
else()
```

after:
```cmake
elseif(WIN32)
    set(NCNN_LIB ${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows_mingw/lib/libncnn.a)
    set(NCNN_INC ${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows_mingw/include/ncnn)
else()
```

**Comment by fengyanWang** [comment]
> The prebuilt library is created using Visual Studio 2019, and I don't think it's compatible with MinGW gcc/g++.
> So, I suggest you build the library using MinGW in your environment (I'm not sure if ncnn can be built with MinGW though...)
> Then, modify the cmake file like the following, assuming you place the created library in `ncnn_prebuilt/x64_windows_mingw`
> 
> before:
> 
> ```cmake
> elseif(MSVC_VERSION)
>     set(NCNN_LIB
>         $<$<CONFIG:Debug>:${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows/lib/ncnnd.lib>
>         $<$<CONFIG:RelWithDebInfo>:${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows/lib/ncnnRelWithDebInfo.lib>
>         $<$<CONFIG:Release>:${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows/lib/ncnn.lib>
>         $<$<CONFIG:MinSizeRel>:${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows/lib/ncnnMinSizeRel.lib>
>     )
>     set(NCNN_INC ${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows/include/ncnn)
> else()
> ```
> 
> after:
> 
> ```cmake
> elseif(WIN32)
>     set(NCNN_LIB ${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows_mingw/lib/libncnn.a)
>     set(NCNN_INC ${CMAKE_CURRENT_LIST_DIR}/../ncnn_prebuilt/x64_windows_mingw/include/ncnn)
> else()
> ```

Thank you for your guidance. According to your reply, I compiled the ncnn source code with MinGW tool, obtained the libncnn. a file, modified the cmake file, and then there was no problem with the compilation and link, but the generated .exe file could not run. I don't know where the problem occurred.

![image](https://user-images.githubusercontent.com/36984088/132931630-398d0fdc-f864-4add-9e1a-1441143ba888.png)
